# Generated by Django 3.2.14 on 2022-07-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('url_adress', models.CharField(blank=True, max_length=200)),
                ('guid', models.CharField(blank=True, max_length=200)),
                ('creator_name', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(null=True)),
                ('image_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='newest',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newest',
            name='creator_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newest',
            name='guid',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newest',
            name='image_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='newest',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='newest',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='newest',
            name='url_adress',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
